### ISSUE TITLE
Expose GBM instance used by randomFinancial

### ISSUE THREAD

**Issue by d3zza** [d3fc/d3fc-random-data#23]
Although a standalone GBM (Geometric Brownian Motion) instance allows for an alternate source of randomNormal it doesn't seem possible to supply it to the default GBM instance used by randomFinancial. It would be great if this was possible as I would like to use randomFinancial with a seeded PRNG.

**Comment by ColinEberhardt** [comment]
that's a good suggestions, we'll look to include that in a release shortly

**Comment by d3zza** [comment]
Nice one. Thank you!

**Comment by msuperina** [comment]
I can pick up this one.
